# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help make automated releases for this project
# ----------------------------------------------------------------------------
# Created By  : Lakshma Kasu
# Created Date: 01/04/2023
# version ='1.0'
# ----------------------------------------------------------------------------

name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10.10'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build
    - name: Build
      run: python -m build .
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        skip_existing: true
